apiVersion: v1
kind: Secret
metadata:
  name: pulsewatch-secrets
  namespace: pulsewatch
type: Opaque
stringData:
  TSDB_USER: "pulsewatch"
  TSDB_PASSWORD: "changeme"
  DATABASE_URL: "postgresql://pulsewatch:changeme@timescaledb.pulsewatch.svc.cluster.local:5432/pulsewatch?sslmode=disable"
